// Couple OS — Shared Package
// Constants and Zod schemas for form validation only.
// Entity types come from apps/mobile/types/database.ts (generated by Supabase).

import { z } from "zod";

// ─────────────────────────────────────────
// CONSTANTS
// ─────────────────────────────────────────

/**
 * @deprecated Categories live in the `expense_categories` table since
 * migration 008. Use `useCategories()` on the client and
 * DEFAULT_EXPENSE_CATEGORIES below as the offline fallback.
 * Removed in Phase 7.
 */
export const EXPENSE_CATEGORIES = [
  "Affitto",
  "Bollette",
  "Spesa",
  "Ristoranti",
  "Trasporti",
  "Salute",
  "Intrattenimento",
  "Altro",
] as const;

export type ExpenseCategory = (typeof EXPENSE_CATEGORIES)[number];

export const EXPENSE_KINDS = ["FIXED", "VARIABLE"] as const;
export type ExpenseKind = (typeof EXPENSE_KINDS)[number];

export const RECURRENCE_FREQUENCIES = [
  "WEEKLY",
  "MONTHLY",
  "BIMONTHLY",
  "QUARTERLY",
  "SEMIANNUAL",
  "ANNUAL",
] as const;
export type RecurrenceFrequency = (typeof RECURRENCE_FREQUENCIES)[number];

export const RECURRENCE_LABELS: Record<RecurrenceFrequency, string> = {
  WEEKLY: "Weekly",
  MONTHLY: "Monthly",
  BIMONTHLY: "Every 2 months",
  QUARTERLY: "Every 3 months",
  SEMIANNUAL: "Every 6 months",
  ANNUAL: "Yearly",
};

export const MEMBER_ROLES = ["OWNER", "MEMBER", "VIEWER"] as const;
export type MemberRole = (typeof MEMBER_ROLES)[number];

/**
 * The 12 system presets seeded by migration 008. Used for seeding and as an
 * offline fallback — the source of truth is `expense_categories`.
 */
export const DEFAULT_EXPENSE_CATEGORIES = [
  { slug: "rent",          label: "Rent / Mortgage", emoji: "🏠", color: "#0ea5e9", kind: "FIXED" },
  { slug: "utilities",     label: "Utilities",       emoji: "💡", color: "#f59e0b", kind: "FIXED" },
  { slug: "subscriptions", label: "Subscriptions",   emoji: "📺", color: "#8b5cf6", kind: "FIXED" },
  { slug: "insurance",     label: "Insurance",       emoji: "🛡️", color: "#64748b", kind: "FIXED" },
  { slug: "groceries",     label: "Groceries",       emoji: "🛒", color: "#10b981", kind: "VARIABLE" },
  { slug: "dining",        label: "Eating out",      emoji: "🍕", color: "#ef4444", kind: "VARIABLE" },
  { slug: "transport",     label: "Transport",       emoji: "🚗", color: "#3b82f6", kind: "VARIABLE" },
  { slug: "health",        label: "Health",          emoji: "💊", color: "#ec4899", kind: "VARIABLE" },
  { slug: "entertainment", label: "Fun",             emoji: "🎉", color: "#f97316", kind: "VARIABLE" },
  { slug: "shopping",      label: "Shopping",        emoji: "👕", color: "#a855f7", kind: "VARIABLE" },
  { slug: "home",          label: "Home & upkeep",   emoji: "🔧", color: "#14b8a6", kind: "VARIABLE" },
  { slug: "other",         label: "Other",           emoji: "📦", color: "#9ca3af", kind: "VARIABLE" },
] as const satisfies readonly { slug: string; label: string; emoji: string; color: string; kind: ExpenseKind }[];

export const PANTRY_CATEGORIES = ["FRIDGE", "FREEZER", "PANTRY", "BATHROOM", "OTHER"] as const;

export const CHECK_IN_PROMPTS = {
  weekly: [
    "How did you feel this week?",
    "Is there anything you'd like to tell me but haven't yet?",
    "What was the best moment of this week together?",
  ],
  monthly: [
    "Is there anything we could do better as a couple this month?",
    "What are you hoping for next month?",
    "What do you appreciate most about me right now?",
  ],
  yearly: [
    "What made you happiest in the past year together?",
    "What's your biggest dream for our future?",
  ],
} as const;

export const PRIORITY_LEVELS = ["LOW", "MEDIUM", "HIGH"] as const;
export const TODO_STATUSES = ["TODO", "IN_PROGRESS", "DONE"] as const;
export const CHECKIN_PERIODS = ["weekly", "monthly", "yearly"] as const;
export const SPLIT_MODES = ["EQUAL", "PROPORTIONAL", "CUSTOM"] as const;

export const SPLIT_MODE_LABELS: Record<(typeof SPLIT_MODES)[number], string> = {
  EQUAL: "Split equally",
  PROPORTIONAL: "Split by income",
  CUSTOM: "Custom shares",
};

// ─────────────────────────────────────────
// FORM SCHEMAS (Zod — for React Hook Form)
// ─────────────────────────────────────────

export const CreatePostSchema = z.object({
  content: z.string().min(1, "The message cannot be empty").max(500, "500 characters max"),
  tags: z.array(z.string()).default([]),
});
export type CreatePostForm = z.infer<typeof CreatePostSchema>;

export const CreateEventSchema = z.object({
  title: z.string().min(1, "A title is required").max(200),
  description: z.string().max(1000).optional(),
  location: z.string().max(300).optional(),
  start_at: z.string().min(1, "A start date is required"),
  end_at: z.string().min(1, "An end date is required"),
  all_day: z.boolean().default(false),
  color: z.string().optional(),
  reminder_minutes: z.array(z.number()).default([]),
});
export type CreateEventForm = z.infer<typeof CreateEventSchema>;

export const CreateTodoListSchema = z.object({
  name: z.string().min(1, "A name is required").max(100),
  emoji: z.string().optional(),
});
export type CreateTodoListForm = z.infer<typeof CreateTodoListSchema>;

export const CreateTodoItemSchema = z.object({
  title: z.string().min(1, "A title is required").max(300),
  description: z.string().max(1000).optional(),
  deadline: z.string().optional(),
  priority: z.enum(["LOW", "MEDIUM", "HIGH"]).default("MEDIUM"),
  assignee_id: z.string().uuid().optional(),
});
export type CreateTodoItemForm = z.infer<typeof CreateTodoItemSchema>;

export const CreatePantryItemSchema = z.object({
  name: z.string().min(1, "A name is required").max(200),
  quantity: z.number().positive().optional(),
  unit: z.string().max(50).optional(),
  expires_at: z.string().optional(),
  category: z.enum(["FRIDGE", "FREEZER", "PANTRY", "BATHROOM", "OTHER"]).default("PANTRY"),
});
export type CreatePantryItemForm = z.infer<typeof CreatePantryItemSchema>;

export const CreateShoppingItemSchema = z.object({
  name: z.string().min(1, "A name is required").max(200),
  quantity: z.number().positive().optional(),
  unit: z.string().max(50).optional(),
  notes: z.string().max(300).optional(),
  category: z.enum(["FRIDGE", "FREEZER", "PANTRY", "BATHROOM", "OTHER"]).default("OTHER"),
});
export type CreateShoppingItemForm = z.infer<typeof CreateShoppingItemSchema>;

export const CreateRecipeSchema = z.object({
  title: z.string().min(1, "A title is required").max(200),
  description: z.string().max(5000).optional(),
  servings: z.number().int().positive().optional(),
  ingredients: z.array(z.object({
    name: z.string().min(1),
    quantity: z.string().optional(),
  })).default([]),
});
export type CreateRecipeForm = z.infer<typeof CreateRecipeSchema>;

export const CreateExpenseSchema = z.object({
  amount: z.number().positive("The amount must be positive"),
  category: z.string().min(1, "A category is required"),
  note: z.string().max(300).optional(),
  date: z.string().default(() => new Date().toISOString().split("T")[0]),
});
export type CreateExpenseForm = z.infer<typeof CreateExpenseSchema>;

export const CreateBudgetSchema = z.object({
  category: z.string().min(1),
  amount: z.number().positive(),
  month: z.number().int().min(1).max(12),
  year: z.number().int().min(2020),
});
export type CreateBudgetForm = z.infer<typeof CreateBudgetSchema>;

export const CreateGoalSchema = z.object({
  title: z.string().min(1, "A title is required").max(200),
  target_amount: z.number().positive("The target must be positive"),
  target_date: z.string().optional(),
  monthly_allocation: z.number().min(0).default(0),
  emoji: z.string().max(8).optional(),
});
export type CreateGoalForm = z.infer<typeof CreateGoalSchema>;

export const RespondCheckInSchema = z.object({
  mood: z.number().int().min(1).max(5),
  response: z.string().min(1, "An answer is required").max(2000),
});
export type RespondCheckInForm = z.infer<typeof RespondCheckInSchema>;

export const CreateMemorySchema = z.object({
  content: z.string().max(5000).optional(),
  tags: z.array(z.string().max(50)).max(20).default([]),
  date: z.string().default(() => new Date().toISOString().split("T")[0]),
  photos: z.array(z.string()).max(5, "5 photos max per memory").default([]),
});
export type CreateMemoryForm = z.infer<typeof CreateMemorySchema>;

// ─────────────────────────────────────────
// BUDGET OS
// ─────────────────────────────────────────

const HEX_COLOR = /^#[0-9a-f]{6}$/i;

export const CreateCategorySchema = z.object({
  label: z.string().min(1, "A name is required").max(60),
  emoji: z.string().max(8).optional(),
  color: z.string().regex(HEX_COLOR, "Use a hex colour like #10b981").optional(),
  kind: z.enum(EXPENSE_KINDS).default("VARIABLE"),
});
export type CreateCategoryForm = z.infer<typeof CreateCategorySchema>;

export const CreateRecurringExpenseSchema = z
  .object({
    label: z.string().min(1, "A name is required").max(120),
    amount: z.number().positive("The amount must be positive"),
    category_id: z.string().uuid("Pick a category"),
    paid_by_member_id: z.string().uuid().optional(),
    frequency: z.enum(RECURRENCE_FREQUENCIES).default("MONTHLY"),
    day_of_month: z.number().int().min(-1).max(31).optional(),
    day_of_week: z.number().int().min(0).max(6).optional(),
    start_date: z.string().min(1, "A start date is required"),
    end_date: z.string().optional(),
    auto_post: z.boolean().default(true),
    variable_amount: z.boolean().default(false),
    note: z.string().max(300).optional(),
  })
  .refine((v) => v.frequency !== "WEEKLY" || v.day_of_week != null, {
    message: "Pick a day of the week",
    path: ["day_of_week"],
  })
  .refine((v) => !v.end_date || v.end_date >= v.start_date, {
    message: "The end date comes before the start date",
    path: ["end_date"],
  });
export type CreateRecurringExpenseForm = z.infer<typeof CreateRecurringExpenseSchema>;

export const CreateHouseholdMemberSchema = z.object({
  display_name: z.string().min(1, "A name is required").max(80),
  avatar_emoji: z.string().max(8).optional(),
  color: z.string().regex(HEX_COLOR, "Use a hex colour like #10b981").optional(),
  role: z.enum(MEMBER_ROLES).default("MEMBER"),
  monthly_income: z.number().min(0).optional(),
});
export type CreateHouseholdMemberForm = z.infer<typeof CreateHouseholdMemberSchema>;

export const SetBudgetLineSchema = z.object({
  category_id: z.string().uuid("Pick a category"),
  amount: z.number().min(0, "The amount cannot be negative"),
  rollover_enabled: z.boolean().default(false),
});
export type SetBudgetLineForm = z.infer<typeof SetBudgetLineSchema>;
